#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn test && yarn lint && yarn format

BRANCH=$(git branch --show-current)
MASTER="master"

git pull origin $BRANCH

if ($BRANCH!=$MASTER)
then
	echo "Pushing branch "$BRANCH" to origin"
	git push origin $BRANCH
else
	echo "You don't want to push to master"
fi
