#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn test && yarn lint && yarn format

BRANCH=$(git branch --show-current)
MASTER="master"

echo "Pushing branch "$BRANCH" to origin"
git push origin $BRANCH
